name: Release
on:
  push:
    branches:
      - test
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Genarate QrCode
        uses: iChengbo/generate-qrcode@v0.1.1
        id: getQrcode
        with:
          text: https://cdn.jsdelivr.net/gh/iChengbo/react-native-imagemin-asset-plugin/package.json
      - name: echo path
        run: echo "${{ steps.getQRCode.outputs.QR_CODE_PNG_PATH }}"
      - name: Upload Image
        uses: actions/upload-artifact@v2
        with:
          name: qrcode
          path: ${{ steps.getQRCode.outputs.QR_CODE_PNG_PATH }}
      # - name: Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: npx semantic-release
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: 测试一下了啦
          files: |
            ${{ steps.getQRCode.outputs.QR_CODE_PNG_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}